name: Daily Kakao News Briefing

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-news-briefing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests python-dotenv

      - name: Run Kakao news bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          KAKAO_TOKEN: ${{ secrets.KAKAO_TOKEN }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
        run: |
         python run_bot.py
